### ISSUE TITLE
Front-End: project structure

### ISSUE THREAD

**Issue by ParleJe** [Koci0/code-matcher#6]
Check it out and give feedback: [faq-structure](https://reactjs.org/docs/faq-structure.html)
With core components to go it's better to standarize structure across all programmers. I know it's late, but better late than never

@AleksandraL99 @uniQueSense and anyone working on frontend :D 

_Originally posted by @ParleJe in https://github.com/Koci0/code-matcher/pull/5#issuecomment-832525190_

**Comment by uniQueSense** [comment]
Grouping by features or routes
